### ISSUE TITLE
UnboundLocalError: local variable 'log' referenced before assignment

### ISSUE THREAD

**Issue by nrayamaj** [lauguma/GWideCodeML#2]
Hi,

I was trying to use GWideCodeML. I got the following error: UnboundLocalError: local variable 'log' referenced before assignment.

I took a piece of code -- for instance function lnl(codeml_in) -- and then reran with and without initializing local variable "log" in the function lnl((), I was able reproduce the error by not initializing the log variable.

Can you let me know if there is a bug (the one I mention) in the program?

Best,
Niraj

**Comment by lauguma** [comment]
Dear Niraj,

Thank you for using GwideCodeML.

It was indeed a bug in the code that was already fixed. You can clone again the repository and type `python setup.py install ` to get the package with the newest changes.

However, this bug appeared when the function is not able to get a LnL value of the tested hypothesis after running codeml. This means that codeml did not successfully run with any of your provided alignment files. In the fixed version, a warning is printed in the log file (gwidecodeml.log) when this happens. You can run again your analysis and see which are the problematic files. If you don't know why codeml is not running with your files you can send me an example of the alignment files used together with a tree file and branch file and I will tell you which is exactly the problem. 

Best,
Laura

**Comment by nrayamaj** [comment]
Hi Laura,

The program stops because of out of range index in the list through read_branches function in utils.py module.

line 498, in read_branches 
IndexError: list index out of range

Best,
Niraj

**Comment by nrayamaj** [comment]
Hi Laura,

I think you commented out the code that runs codeml in parallel.

#pool = mp.Pool(t)  # number of# threads
        #pool.map(utils.run_codeml, [ctl for ctl in gene_names])
        #pool.close()
        #os.chdir(working_dir) 
        
  Can you please check? I am getting the following message:
  2021-02-11 14:58:20,358 :: INFO :: Starting analysis of 3269 alignments
2021-02-11 14:58:46,294 :: INFO :: Control files successfully created, GWidecodeml is ready for codeml performance
2021-02-11 14:58:46,294 :: INFO :: Codeml has finished, output files successfully created. Running LRTs...
2021-02-11 14:58:46,294 :: INFO :: DEBUGGING

But I DO NOT see any codeml output. It is possibly because the code for running codeml has been commented out.

Best,
Niraj

**Comment by lauguma** [comment]
Dear Niraj,

I want to apologize because I've totally mixed up the versions when I was trying to fix the bug. The code has been updated.

Regarding the error of the branches file, please, make sure that your text file does not contain any blank line.

Thank you for reporting and again, sorry for the inconvenience caused.

Laura

**Comment by nrayamaj** [comment]
Hi Laura,

No problem! Thank you for your good work!

Best,
Niraj
